// import SITE_CONSTANTS from '../siteConstants'

// const names = {
//   arrowDown: 'arrowDown.svg',
//   arrows: 'arrows.svg',
//   avatar: 'avatar.svg',
//   activeAvatar: 'activeAvatar.svg',
//   businessTaxi: 'business-taxi.svg',
//   carAlt: 'car-alt.svg',
//   cash: 'cash.svg',
//   checkMark: 'check-mark.svg',
//   economTaxi: 'econom-taxi.svg',
//   flagRu: 'flag-ru.svg',
//   flagGb: 'flag-gb.svg',
//   flagFr: 'flag-fr.svg',
//   flagMar: 'flag-ma.svg',
//   activeMarker: 'mark-colored.svg',
//   inactiveMarker: 'mark-uncolored.svg',
//   menuIcon: 'menu-icon.svg',
//   messageIcon: 'message-icon.svg',
//   multipleUsers: 'multiple-users.svg',
//   notoTaxi: 'noto-taxi.svg',
//   plusIcon: 'plus-icon.svg',
//   clock: 'clock.svg',
//   driverAvatar: 'driver-avatar.svg',
//   solidCar: 'fa-solid_car.svg',
//   subwayIdCard: 'subway-id-card.svg',
//   card: 'card.svg',
//   stars: 'stars.svg',
//   starEmpty: 'star-empty.svg',
//   starFull: 'star-full.svg',
//   cardIcon: 'card-icon.svg',
//   photoCamera: 'photo-camera.svg',
//   helpIcon: 'help-icon.svg',
//   timer: 'timer.svg',
//   closeIcon: 'close-icon.svg',
//   cardIconGrey: 'card-icon-grey.svg',
//   chatIcon: 'chat-icon.svg',
//   minusCircle: 'minus-circle.svg',
//   minusIcon: 'minus-icon.svg',
//   plusCircle: 'plus-circle.svg',
//   people: 'people.svg',
//   recomended: 'recomended.svg',
//   requested: 'requested.svg',
//   turn: 'turn.svg',
//   uGroup: 'u-group.svg',
//   clockGrey: 'grey-clock.svg',
//   clockGreen: 'clock-green.svg',
//   turnBr: 'turn-br.svg',
//   cardIconBr: 'card-icon-br.svg',
//   chatIconBr: 'chat-icon-br.svg',
//   mapIcon: 'map-icon.svg',
//   mapArrow: 'map-arrow.svg',
//   mapArrowVoting: 'map-arrow-voting.svg',
//   mapOrderVoting: 'map-voting.svg',
//   mapOrderWating: 'map-waiting.svg',
//   mapOrderPerforming: 'map-performing.svg',
//   mapMarkerProfit: 'map-marker-profit.svg',
//   mapArrowHome: 'map-arrow-home.svg',
//   returnIcon: 'return-icon.svg',
//   passengerAvatar: 'passenger-avatar.svg',
//   clockBlue: 'clock-blue.svg',
//   markerGreen: 'marker-green.svg',
//   markerYellow: 'marker-yellow.svg',
//   loading: 'loading.gif',
//   markerFrom: 'marker-from.svg',
//   markerTo: 'marker-to.svg',
//   voting: 'voting.svg',
//   votingRed: 'voting-red.svg',
//   waiting: 'waiting.svg',
//   delivery: 'delivery.svg',
//   light: 'light.svg',
//   truck: 'truck.svg',
//   wagon: 'wagon.svg',
//   foot: 'foot.svg',
//   bicycle: 'bicycle.svg',
//   motorcycle: 'motorcycle.svg',
//   motorcycleRed: 'motorcycle-red.svg',
//   deliveryRed: 'delivery-red.svg',
//   phone: 'phone.svg',
//   bigSize: 'big-size.svg',
//   boxing: 'boxing.svg',
//   openedEye: 'opened-eye.svg',
//   closedEye: 'closed-eye.svg',
//   error: 'error.svg',
//   fetching: 'fetching.svg',
//   move: 'move.svg',
//   apartamentShedule: 'apartamentShedule.svg',
//   handyMoving: 'handyMoving.svg',
//   pickUp: 'pickUp.svg',
//   sameDayPickUp: 'sameDayPickUp.svg',
//   addPhoto: 'addPhoto.svg',
//   trash: 'trash.svg',
//   moveColored: 'moveColored.svg',
//   furniture: 'furniture.png',
//   rooms: 'rooms.png',
//   elevator: 'elevator.png',
//   sliderArrow: 'sliderArrow.svg',
//   chat: 'chat.svg',
//   equal: 'equal.svg',
//   more: 'more.svg',
//   less: 'less.svg',
//   date: 'date.svg',
//   interval: 'interval.svg',
//   largeTruck: 'largeTruck.svg',
//   time: 'time.svg',
//   bigTruck: 'bigTruck.svg',
//   carWash: 'carWash.svg',
//   handUp: 'handup-icon.svg',
//   noImgAvatar: 'no-img-avatar.svg',
//   noUserAvatar: 'no-user-avatar.svg',
//   pointOnMap: 'pointOnMapIcon.svg',
//   callIcon: 'call-icon.svg',
//   moneyIcon: 'money-icon.svg',
//   carIcon: 'car-icon.svg',
//   peopleIcon: 'people-icon.svg',
//   alarmIcon: 'alarm-icon.svg',
//   alarmIconLight: 'alarm-icon-light.svg',
//   carNearbyIcon: 'car-nearby-icon.svg',
//   msgIcon: 'msg-icon.svg',
//   seatSliderArrowRight: 'slider-arrow-right.svg',
//   timeWaitIcon: 'time-wait-icon.svg',
//   checkMarkRed: 'check-mark-red.svg',
//   dollarIcon: 'dollar-icon.svg',
//   arrowDownFrame: 'arrow-down-frame.svg',
//   arrowUpFrame: 'arrow-up-frame.svg',
//   cameraIcon: 'camera-icon.svg',
//   dollarMinimalistic: 'dollarMinimalistic.svg',
//   logo: 'logo.svg',
//   emoji_1: 'emoji_1.png',
//   emoji_2: 'emoji_2.png',
//   emoji_3: 'emoji_3.png',
//   emoji_4: 'emoji_4.png',
//   emoji_5: 'emoji_5.png',
//   emoji_6: 'emoji_6.png',
//   emoji_7: 'emoji_7.png',
//   emoji_7_1: 'emoji_7_1.png',
//   emoji_8: 'emoji_8.png',
// }

// export default new Proxy({}, {
//   get(target, key: keyof typeof names) {
//     return key in names ?
//       `/assets/images/${
//         SITE_CONSTANTS.ICONS_PALETTE_FOLDER &&
//           `${SITE_CONSTANTS.ICONS_PALETTE_FOLDER}/`
//       }${names[key]}` :
//       undefined
//   },
// }) as typeof names





export default {
  // Флаги (PNG)
  flagRu: require('../assets/GHA/flag-ru.svg'),
  flagGb: require('../assets/GHA/flag-gb.svg'),
  flagFr: require('../assets/GHA/flag-fr.svg'),
  flagMar: require('../assets/GHA/flag-ma.svg'),
  
  // Эмодзи (PNG)
  emoji_1: require('../assets/default/emoji_1.png'),
  emoji_2: require('../assets/default/emoji_2.png'),
  emoji_3: require('../assets/default/emoji_3.png'),
  emoji_4: require('../assets/default/emoji_4.png'),
  emoji_5: require('../assets/default/emoji_5.png'),
  emoji_6: require('../assets/default/emoji_6.png'),
  emoji_7: require('../assets/default/emoji_7.png'),
  emoji_7_1: require('../assets/default/emoji_7_1.png'),
  emoji_8: require('../assets/default/emoji_8.png'),

  // Мебель/Комнаты (PNG)
  furniture: require('../assets/GHA/furniture.png'),
  rooms: require('../assets/GHA/rooms.png'),
  elevator: require('../assets/GHA/elevator.png'),
  googleIcon: require('../assets/GHA/google-icon.png'),

  // Загрузка (GIF)
  loading: require('../assets/GHA/loading.gif'),
  
  // Все остальные SVG-файлы
  arrowDown: require('../assets/GHA/arrowDown.svg'),
  arrows: require('../assets/GHA/arrows.svg'),
  avatar: require('../assets/GHA/avatar.svg'),
  activeAvatar: require('../assets/GHA/activeAvatar.svg'),
  businessTaxi: require('../assets/GHA/business-taxi.svg'),
  carAlt: require('../assets/GHA/car-alt.svg'),
  cash: require('../assets/GHA/cash.svg'),
  checkMark: require('../assets/GHA/check-mark.svg'),
  economTaxi: require('../assets/GHA/econom-taxi.svg'),
  activeMarker: require('../assets/GHA/mark-colored.svg'),
  inactiveMarker: require('../assets/GHA/mark-uncolored.svg'),
  menuIcon: require('../assets/GHA/menu-icon.svg'),
  messageIcon: require('../assets/GHA/message-icon.svg'),
  multipleUsers: require('../assets/GHA/multiple-users.svg'),
  notoTaxi: require('../assets/GHA/noto-taxi.svg'),
  plusIcon: require('../assets/GHA/plus-icon.svg'),
  clock: require('../assets/GHA/clock.svg'),
  driverAvatar: require('../assets/GHA/driver-avatar.svg'),
  solidCar: require('../assets/GHA/fa-solid_car.svg'),
  subwayIdCard: require('../assets/GHA/subway-id-card.svg'),
  card: require('../assets/GHA/card.svg'),
  stars: require('../assets/GHA/stars.svg'),
  starEmpty: require('../assets/GHA/star-empty.svg'),
  starFull: require('../assets/GHA/star-full.svg'),
  cardIcon: require('../assets/GHA/card-icon.svg'),
  photoCamera: require('../assets/GHA/photo-camera.svg'),
  helpIcon: require('../assets/GHA/help-icon.svg'),
  timer: require('../assets/GHA/timer.svg'),
  closeIcon: require('../assets/GHA/close-icon.svg'),
  cardIconGrey: require('../assets/GHA/card-icon-grey.svg'),
  chatIcon: require('../assets/GHA/chat-icon.svg'),
  minusCircle: require('../assets/GHA/minus-circle.svg'),
  minusIcon: require('../assets/GHA/minus-icon.svg'),
  plusCircle: require('../assets/GHA/plus-circle.svg'),
  people: require('../assets/GHA/people.svg'),
  recomended: require('../assets/GHA/recomended.svg'),
  requested: require('../assets/GHA/requested.svg'),
  turn: require('../assets/GHA/turn.svg'),
  uGroup: require('../assets/GHA/u-group.svg'),
  clockGrey: require('../assets/GHA/grey-clock.svg'),
  clockGreen: require('../assets/GHA/clock-green.svg'),
  turnBr: require('../assets/GHA/turn-br.svg'),
  cardIconBr: require('../assets/GHA/card-icon-br.svg'),
  chatIconBr: require('../assets/GHA/chat-icon-br.svg'),
  mapIcon: require('../assets/GHA/map-icon.svg'),
  mapArrow: require('../assets/GHA/map-arrow.svg'),
  mapArrowVoting: require('../assets/GHA/map-arrow-voting.svg'),
  mapOrderVoting: require('../assets/GHA/map-voting.svg'),
  mapOrderWating: require('../assets/GHA/map-waiting.svg'),
  mapOrderPerforming: require('../assets/GHA/map-performing.svg'),
  mapMarkerProfit: require('../assets/GHA/map-marker-profit.svg'),
  mapArrowHome: require('../assets/GHA/map-arrow-home.svg'),
  returnIcon: require('../assets/GHA/return-icon.svg'),
  passengerAvatar: require('../assets/GHA/passenger-avatar.svg'),
  clockBlue: require('../assets/GHA/clock-blue.svg'),
  markerGreen: require('../assets/GHA/marker-green.svg'),
  markerYellow: require('../assets/GHA/marker-yellow.svg'),
  markerFrom: require('../assets/GHA/marker-from.svg'),
  markerTo: require('../assets/GHA/marker-to.svg'),
  voting: require('../assets/GHA/voting.svg'),
  votingRed: require('../assets/GHA/voting-red.svg'),
  waiting: require('../assets/GHA/waiting.svg'),
  delivery: require('../assets/GHA/delivery.svg'),
  light: require('../assets/GHA/light.svg'),
  truck: require('../assets/GHA/truck.svg'),
  wagon: require('../assets/GHA/wagon.svg'),
  foot: require('../assets/GHA/foot.svg'),
  bicycle: require('../assets/GHA/bicycle.svg'),
  motorcycle: require('../assets/GHA/motorcycle.svg'),
  motorcycleRed: require('../assets/GHA/motorcycle-red.svg'),
  deliveryRed: require('../assets/GHA/delivery-red.svg'),
  phone: require('../assets/GHA/phone.svg'),
  bigSize: require('../assets/GHA/big-size.svg'),
  boxing: require('../assets/GHA/boxing.svg'),
  openedEye: require('../assets/GHA/opened-eye.svg'),
  closedEye: require('../assets/GHA/closed-eye.svg'),
  error: require('../assets/GHA/error.svg'),
  fetching: require('../assets/GHA/fetching.svg'),
  move: require('../assets/GHA/move.svg'),
  apartamentShedule: require('../assets/GHA/apartamentShedule.svg'),
  handyMoving: require('../assets/GHA/handyMoving.svg'),
  pickUp: require('../assets/GHA/pickUp.svg'),
  sameDayPickUp: require('../assets/GHA/sameDayPickUp.svg'),
  addPhoto: require('../assets/GHA/addPhoto.svg'),
  trash: require('../assets/GHA/trash.svg'),
  moveColored: require('../assets/GHA/moveColored.svg'),
  sliderArrow: require('../assets/GHA/sliderArrow.svg'),
  chat: require('../assets/GHA/chat.svg'),
  equal: require('../assets/GHA/equal.svg'),
  more: require('../assets/GHA/more.svg'),
  less: require('../assets/GHA/less.svg'),
  date: require('../assets/GHA/date.svg'),
  interval: require('../assets/GHA/interval.svg'),
  // largeTruck: require('../assets/GHA/largeTruck.svg'),
  time: require('../assets/GHA/time.svg'),
  bigTruck: require('../assets/GHA/bigTruck.svg'),
  carWash: require('../assets/GHA/carWash.svg'),
  handUp: require('../assets/GHA/handup-icon.svg'),
  noImgAvatar: require('../assets/GHA/no-img-avatar.svg'),
  noUserAvatar: require('../assets/GHA/no-user-avatar.svg'),
  pointOnMap: require('../assets/GHA/pointOnMapIcon.svg'),
  callIcon: require('../assets/GHA/call-icon.svg'),
  moneyIcon: require('../assets/GHA/money-icon.svg'),
  carIcon: require('../assets/GHA/car-icon.svg'),
  peopleIcon: require('../assets/GHA/people-icon.svg'),
  alarmIcon: require('../assets/GHA/alarm-icon.svg'),
  // alarmIconLight: require('../assets/GHA/alarm-icon-light.svg'),
  carNearbyIcon: require('../assets/GHA/car-nearby-icon.svg'),
  msgIcon: require('../assets/GHA/msg-icon.svg'),
  seatSliderArrowRight: require('../assets/GHA/slider-arrow-right.svg'),
  timeWaitIcon: require('../assets/GHA/time-wait-icon.svg'),
  checkMarkRed: require('../assets/GHA/check-mark-red.svg'),
  dollarIcon: require('../assets/GHA/dollar-icon.svg'),
  arrowDownFrame: require('../assets/GHA/arrow-down-frame.svg'),
  arrowUpFrame: require('../assets/GHA/arrow-up-frame.svg'),
  cameraIcon: require('../assets/GHA/camera-icon.svg'),
  dollarMinimalistic: require('../assets/GHA/dollarMinimalistic.svg'),
  logo: require('../assets/GHA/logo.svg'),
}